default:
  image: registry.gitlab.com/gitlab-org/gitlab-build-images:gitlab-charts-build-base
  tags:
  - gitlab-org

variables:
  GIT_CLONE_PATH: $CI_BUILDS_DIR/gitlab-runner

stages:
- test
- release

lint:
  stage: test
  script:
  - helm lint .

release development:
  stage: release
  script:
  - helm init --client-only
  - helm package .
  when: manual
  only:
  - branches
  except:
  - master
  artifacts:
    paths:
    - gitlab-runner*.tgz
    expire_in: 7d

release beta:
  stage: release
  variables:
    S3_URL: s3://${S3_BUCKET}${S3_PATH}
    REPO_URL: https://${S3_BUCKET}.s3.amazonaws.com${S3_PATH}
  script:
  - apk add --no-cache py-pip
  - pip install awscli
  - helm init --client-only
  - 'beta_info=$(git describe --long | sed -r "s/v[0-9\.]+(-rc[0-9]+)?-//")'
  - 'build_time=$(date +%s)'
  - 'sed -r "s/(version: [0-9\.]+-beta)/\1-${build_time}-${beta_info}/" -i Chart.yaml'
  - 'sed -r "s/appVersion: .*/appVersion: bleeding/" -i Chart.yaml'
  - 'sed -r "s/imagePullPolicy: IfNotPresent/imagePullPolicy: Always/" -i values.yaml'
  - mkdir -p public/
  - aws s3 cp ${S3_URL}/index.yaml public/index.yaml || true
  - (cd public; helm package ../)
  - helm repo index public --merge public/index.yaml --url ${REPO_URL}
  - aws s3 sync public ${S3_URL} --acl public-read
  - 'echo "To install repository run: helm repo add gitlab-runner-beta ${REPO_URL} && helm repo update"'
  only:
  - master@gitlab-org/charts/gitlab-runner

release stable:
  stage: release
  script:
  - curl --request POST
         --form "token=$CI_JOB_TOKEN"
         --form ref=master
         --form "variables[CHART_NAME]=$CI_PROJECT_NAME"
         --form "variables[RELEASE_REF]=$CI_COMMIT_REF_NAME"
         https://gitlab.com/api/v4/projects/2860651/trigger/pipeline
  rules:
  - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+(-rc[0-9]+)?$/ && $CI_PROJECT_URL == "https://gitlab.com/gitlab-org/charts/gitlab-runner"'
  - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+(-rc[0-9]+)?$/ && $CI_PROJECT_URL == "https://gitlab.com/gitlab-org/security/charts/gitlab-runner"'
