image: nginx:1.14.2

stages:
  - build
  - deploy

build-dev:
  stage: build
  script:
    - echo "Building the image and pushing to GCR.."
  tags:
    - runner-private

deploy-dev:
  stage: deploy
  script:
    - gcloud container clusters get-credentials terraform-team-test-private-gke --region us-east1 --project deimos-internal-playground
    - kubectl apply -f dev/ -n $NAMESPACE
  tags:
    - runner-private
