image: nginx:1.14.2

stages:
  - build
  - deploy

variables:
  GKE_CLUSTER: "terraform-team-test-private-gke"
  CLUSTER_GKE_REGION: "us-east1"
  PROJECT_ID: "deimos-internal-playground"

build-dev:
  stage: build
  script:
    - echo "Building the image and pushing to GCR.."
  tags:
    - runner-private

deploy-dev:
  stage: deploy
  script:
    - gcloud container clusters get-credentials $GKE_CLUSTER --region $CLUSTER_GKE_REGION --project $PROJECT_ID
    - kubectl apply -f dev/ -n $NAMESPACE
  tags:
    - runner-private
