image: nginx:1.14.2

variables:
  GOOGLE_APPLICATION_CREDENTIALS: $DEV_AUTH_REGISTERY_SERVER
  GKE_CLUSTER: terraform-team-test-private-gke
  GKE_REGION: us-east1
  PROJECT_ID: deimos-internal-playground

stages:
  - build
  - deploy

build-dev:
  stage: build
  script:
    - echo "Building the image and pushing to GCR.."
  tags:
    - runner-private

deploy-dev:
  stage: deploy
  script:
    - apt update
    - apt install -y curl python python3
    - curl -LO https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-367.0.0-linux-x86_64.tar.gz
    - tar xvfz google-cloud-sdk-367.0.0-linux-x86_64.tar.gz
    - ./google-cloud-sdk/install.sh
    - ./google-cloud-sdk/bin/gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
    - ./google-cloud-sdk/bin/gcloud container clusters get-credentials terraform-team-test-private-gke --region us-east1 --project deimos-internal-playground
    - apt-get install -y apt-transport-https ca-certificates curl
    - apt-get install -y kubectl
    - kubectl apply -f dev/ -n $NAMESPACE
  tags:
    - runner-private
