include:
  - template: Terraform/.gitlab-ci.yml

stages:
  - build
  - deploy

build-dev:
  stage: build
  script:
    - echo "Building the image and pushing to GCR..."

deploy-dev:
  stage: deploy
  script:
    - gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
    - gcloud container clusters get-credentials $PUBLIC_OLD_GKE_CLUSTER --region $OLD_CLUSTER_GKE_REGION --project $UPGRADED_PROJECT_ID
    - kubectl apply -f dev/ -n $NAMESPACE
