name: Terraform Modules CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v1

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.13.7

    - name: Run a Terraform init
      run: terraform init

    - name: Run a Terraform validate
      run: terraform validate

    - name: Run a Terraform fmt -check
      run: terraform fmt -check

    - uses: terraform-linters/setup-tflint@v1
      name: Setup TFLint

    - name: Run TFLint
      run: tflint
