apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
---
apiVersion: v1
kind: Service
metadata:
  name: simple-web-app
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 32411

    