apiVersion: apps/v1
kind: depoyment
metadata:
  name: simple-web-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: app
        image: simple-web-app:latest
---
apiVersion: v1
kind: Service
metadata:
  name: simple-web-app
  namespace: default
spec:
  type: LoadBalancer
  selector:
    bb: web
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 32411

    