apiVersion: apps/v1
kind: depoyment
metadata:
  name: simple-web-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: simple-web-app
        image: gcr.io/deimos-internal-playground/simple-web-app@sha256:ec0d6968d7d251943f21857ef87125debe5078ec954c425ef5d6c4c6d60908f3
---
apiVersion: v1
kind: Service
metadata:
  name: simple-web-app
  namespace: default
spec:
  type: LoadBalancer
  selector:
    bb: web
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 32411

    